package com.bosslevels;
import java.util.List;

public enum BossDefinition
{
    ABYSSAL_SIRE(
            "Abyssal Sire",
            "abyssal_sire",
            1102,
            "game_icon_abyssalsire.png",
            List.of(
                    "Level 63: You had a 50% chance to obtain an Abyssal dagger",
                    "Level 66: You are on rate to obtain an Abyssal dagger",
                    "Level 68: You had a 50% chance to obtain the Abyssal bludgeon",
                    "Level 70: You are on rate to obtain the Abyssal bludgeon",
                    "Level 70: You had a 50% chance to obtain a Jar of miasma",
                    "Level 70: You had a 50% chance to obtain an Abyssal whip",
                    "Level 72: You had a 50% chance to obtain an Abyssal head",
                    "Level 73: You are on rate to obtain a Jar of miasma",
                    "Level 74: You are on rate to obtain an Abyssal whip",
                    "Level 74: You had a 50% chance to Complete Abyssal Sire",
                    "Level 76: You are on rate to Complete Abyssal Sire",
                    "Level 76: You are on rate to obtain an Abyssal head",
                    "Level 79: You had a 50% chance to obtain Abyssal orphan",
                    "Level 79: You had a 99% chance to obtain the Abyssal bludgeon",
                    "Level 82: You had a 99% chance to obtain an Abyssal dagger",
                    "Level 83: You are on rate to obtain Abyssal orphan",
                    "Level 84: You had a 50% chance to Green Log Abyssal Sire",
                    "Level 86: You are on rate to Green Log Abyssal Sire",
                    "Level 89: You had a 99% chance to obtain a Jar of miasma",
                    "Level 90: You had a 99% chance to Complete Abyssal Sire",
                    "Level 90: You had a 99% chance to obtain an Abyssal whip",
                    "Level 91: You had a 99% chance to obtain an Abyssal head",
                    "Level 98: You had a 99% chance to obtain Abyssal orphan",
                    "Level 99: You had a 99% chance to Green Log Abyssal Sire"
            )
    ),
    ALCHEMICAL_HYDRA(
            "Alchemical Hydra",
            "alchemical_hydra",
            925,
            "game_icon_alchemicalhydra.png",
            List.of(
                    "Level 54: You had a 50% chance to obtain Alchemical hydra heads",
                    "Level 58: You are on rate to obtain Alchemical hydra heads",
                    "Level 61: You had a 50% chance to obtain a Hydra leather",
                    "Level 61: You had a 50% chance to obtain a Hydra tail",
                    "Level 64: You had a 50% chance to obtain the Brimstone ring",
                    "Level 65: You are on rate to obtain a Hydra leather",
                    "Level 65: You are on rate to obtain a Hydra tail",
                    "Level 67: You are on rate to obtain the Brimstone ring",
                    "Level 68: You had a 50% chance to obtain a Hydra's claw",
                    "Level 72: You are on rate to obtain a Hydra's claw",
                    "Level 73: You had a 50% chance to Complete Alchemical Hydra",
                    "Level 73: You had a 99% chance to obtain Alchemical hydra heads",
                    "Level 75: You are on rate to Complete Alchemical Hydra",
                    "Level 75: You had a 50% chance to obtain a Jar of chemicals",
                    "Level 76: You had a 99% chance to obtain the Brimstone ring",
                    "Level 79: You are on rate to obtain a Jar of chemicals",
                    "Level 79: You had a 50% chance to obtain Ikkle hydra",
                    "Level 80: You had a 99% chance to obtain a Hydra leather",
                    "Level 80: You had a 99% chance to obtain a Hydra tail",
                    "Level 83: You are on rate to obtain Ikkle hydra",
                    "Level 84: You had a 50% chance to Green Log Alchemical Hydra",
                    "Level 86: You are on rate to Green Log Alchemical Hydra",
                    "Level 87: You had a 99% chance to Complete Alchemical Hydra",
                    "Level 87: You had a 99% chance to obtain a Hydra's claw",
                    "Level 94: You had a 99% chance to obtain a Jar of chemicals",
                    "Level 98: You had a 99% chance to obtain Ikkle hydra",
                    "Level 99: You had a 99% chance to Green Log Alchemical Hydra"
            )
    ),
    AMOXLIATL(
            "Amoxliatl",
            "amoxliatl",
            943,
            "game_icon_amoxliatl.png",
                List.of(
                        "Level 31: You had a 50% chance to obtain a Pendant of ates",
                        "Level 35: You are on rate to obtain a Pendant of ates",
                        "Level 45: You had a 50% chance to obtain the Glacial temotli",
                        "Level 46: You had a 50% chance to Complete Amoxliatl",
                        "Level 49: You are on rate to Complete Amoxliatl",
                        "Level 49: You are on rate to obtain the Glacial temotli",
                        "Level 50: You had a 99% chance to obtain a Pendant of ates",
                        "Level 64: You had a 99% chance to Complete Amoxliatl",
                        "Level 64: You had a 99% chance to obtain the Glacial temotli",
                        "Level 79: You had a 50% chance to Green Log Amoxliatl",
                        "Level 79: You had a 50% chance to obtain Moxi",
                        "Level 83: You are on rate to Green Log Amoxliatl",
                        "Level 83: You are on rate to obtain Moxi",
                        "Level 98: You had a 99% chance to obtain Moxi",
                        "Level 99: You had a 99% chance to Green Log Amoxliatl"
                )
                ),
    ARAXXOR(
            "Araxxor",
            "araxxor",
            941,
            "game_icon_araxxor.png",
            List.of(
                    "Level 54: You had a 50% chance to obtain Araxyte head",
                    "Level 58: You are on rate to obtain Araxyte head",
                    "Level 63: You had a 50% chance to obtain an Araxyte fang",
                    "Level 66: You had a 50% chance to obtain the Noxious halberd",
                    "Level 67: You are on rate to obtain an Araxyte fang",
                    "Level 68: You are on rate to obtain the Noxious halberd",
                    "Level 69: You had a 50% chance to Complete Araxxor",
                    "Level 71: You are on rate to Complete Araxxor",
                    "Level 72: You had a 50% chance to obtain Jar of venom",
                    "Level 73: You had a 99% chance to obtain Araxyte head",
                    "Level 76: You are on rate to obtain Jar of venom",
                    "Level 77: You had a 99% chance to obtain the Noxious halberd",
                    "Level 79: You had a 50% chance to obtain Nid",
                    "Level 82: You had a 50% chance to Green Log Araxxor",
                    "Level 82: You had a 99% chance to Complete Araxxor",
                    "Level 82: You had a 99% chance to obtain an Araxyte fang",
                    "Level 83: You are on rate to obtain Nid",
                    "Level 85: You are on rate to Green Log Araxxor",
                    "Level 91: You had a 99% chance to obtain Jar of venom",
                    "Level 98: You had a 99% chance to obtain Nid",
                    "Level 99: You had a 99% chance to Green Log Araxxor"
            )
    ),
    ARTIO(
            "Artio",
            "artio",
            1010,
            "game_icon_artio.png",
            List.of(
                    "Level 59: You had a 50% chance to obtain a Dragon 2h sword",
                    "Level 59: You had a 50% chance to obtain a Dragon pickaxe",
                    "Level 62: You are on rate to obtain a Dragon 2h sword",
                    "Level 62: You are on rate to obtain a Dragon pickaxe",
                    "Level 64: You had a 50% chance to obtain The Claws of callisto",
                    "Level 66: You had a 50% chance to obtain The Tyrannical ring",
                    "Level 68: You are on rate to obtain The Claws of callisto",
                    "Level 68: You had a 50% chance to obtain The Voidwaker hilt",
                    "Level 69: You are on rate to obtain The Tyrannical ring",
                    "Level 72: You are on rate to obtain The Voidwaker hilt",
                    "Level 75: You had a 50% chance to Complete Artio",
                    "Level 77: You are on rate to Complete Artio",
                    "Level 78: You had a 99% chance to obtain a Dragon 2h sword",
                    "Level 78: You had a 99% chance to obtain a Dragon pickaxe",
                    "Level 79: You had a 50% chance to obtain Callisto cub",
                    "Level 81: You had a 50% chance to Green Log Artio",
                    "Level 83: You are on rate to obtain Callisto cub",
                    "Level 83: You had a 99% chance to obtain The Claws of callisto",
                    "Level 84: You are on rate to Green Log Artio",
                    "Level 85: You had a 99% chance to obtain The Tyrannical ring",
                    "Level 87: You had a 99% chance to obtain The Voidwaker hilt",
                    "Level 88: You had a 99% chance to Complete Artio",
                    "Level 98: You had a 99% chance to obtain Callisto cub",
                    "Level 99: You had a 99% chance to Green Log Artio"
            )
    ),
    BRYOPHYTA(
            "Bryophyta",
            "bryophyta",
            1606,
            "game_icon_bryophyta.png",
            List.of(
                    "Level 79: You had a 50% chance to Green Log Bryophyta",
                    "Level 83: You are on rate to Green Log Bryophyta",
                    "Level 99: You had a 99% chance to Green Log Bryophyta"
            )
    ),
    CALLISTO(
            "Callisto",
            "callisto",
            1887,
            "game_icon_callisto.png",
            List.of(
                    "Level 59: You had a 50% chance to obtain The Claws of callisto",
                    "Level 62: You had a 50% chance to obtain a Dragon 2h sword",
                    "Level 62: You had a 50% chance to obtain a Dragon pickaxe",
                    "Level 63: You are on rate to obtain The Claws of callisto",
                    "Level 65: You are on rate to obtain a Dragon 2h sword",
                    "Level 65: You are on rate to obtain a Dragon pickaxe",
                    "Level 65: You had a 50% chance to obtain a Voidwaker hilt",
                    "Level 69: You are on rate to obtain a Voidwaker hilt",
                    "Level 69: You had a 50% chance to obtain The Tyrannical ring",
                    "Level 72: You are on rate to obtain The Tyrannical ring",
                    "Level 75: You had a 50% chance to Complete Callisto",
                    "Level 77: You are on rate to Complete Callisto",
                    "Level 78: You had a 99% chance to obtain The Claws of callisto",
                    "Level 79: You had a 50% chance to obtain Callisto cub",
                    "Level 81: You had a 50% chance to Green Log Callisto",
                    "Level 81: You had a 99% chance to obtain a Dragon 2h sword",
                    "Level 81: You had a 99% chance to obtain a Dragon pickaxe",
                    "Level 83: You are on rate to obtain Callisto cub",
                    "Level 84: You are on rate to Green Log Callisto",
                    "Level 84: You had a 99% chance to obtain a Voidwaker hilt",
                    "Level 88: You had a 99% chance to Complete Callisto",
                    "Level 88: You had a 99% chance to obtain The Tyrannical ring",
                    "Level 98: You had a 99% chance to obtain Callisto cub",
                    "Level 99: You had a 99% chance to Green Log Callisto"
            )
    ),
    CALVARION(
            "Calvar'ion",
            "calvarion",
            1010,
            "game_icon_calvarion.png",
            List.of(
                    "Level 59: You had a 50% chance to obtain a Dragon 2h sword",
                    "Level 59: You had a 50% chance to obtain a Dragon pickaxe",
                    "Level 62: You are on rate to obtain a Dragon 2h sword",
                    "Level 62: You are on rate to obtain a Dragon pickaxe",
                    "Level 64: You had a 50% chance to obtain The Skull of vet'ion",
                    "Level 66: You had a 50% chance to obtain The Ring of the gods",
                    "Level 68: You are on rate to obtain The Skull of vet'ion",
                    "Level 68: You had a 50% chance to obtain a Voidwaker blade",
                    "Level 69: You are on rate to obtain The Ring of the gods",
                    "Level 72: You are on rate to obtain a Voidwaker blade",
                    "Level 75: You had a 50% chance to Complete Calvar'ion",
                    "Level 77: You are on rate to Complete Calvar'ion",
                    "Level 78: You had a 99% chance to obtain a Dragon 2h sword",
                    "Level 78: You had a 99% chance to obtain a Dragon pickaxe",
                    "Level 79: You had a 50% chance to obtain Vet'ion jr.",
                    "Level 81: You had a 50% chance to Green Log Calvar'ion",
                    "Level 83: You are on rate to obtain Vet'ion jr.",
                    "Level 83: You had a 99% chance to obtain The Skull of vet'ion",
                    "Level 84: You are on rate to Green Log Calvar'ion",
                    "Level 85: You had a 99% chance to obtain The Ring of the gods",
                    "Level 87: You had a 99% chance to obtain a Voidwaker blade",
                    "Level 88: You had a 99% chance to Complete Calvar'ion",
                    "Level 98: You had a 99% chance to obtain Vet'ion jr.",
                    "Level 99: You had a 99% chance to Green Log Calvar'ion"
            )
    ),
    CERBERUS(
            "Cerberus",
            "cerberus",
            925,
            "game_icon_cerberus.png",
            List.of(
                    "Level 62: You had a 50% chance to obtain a Pegasian crystal",
                    "Level 62: You had a 50% chance to obtain a Primordial crystal",
                    "Level 62: You had a 50% chance to obtain an Eternal crystal",
                    "Level 62: You had a 50% chance to obtain Smouldering stone",
                    "Level 65: You are on rate to obtain a Pegasian crystal",
                    "Level 65: You are on rate to obtain a Primordial crystal",
                    "Level 65: You are on rate to obtain an Eternal crystal",
                    "Level 65: You are on rate to obtain Smouldering stone",
                    "Level 71: You had a 50% chance to Complete Cerberus",
                    "Level 73: You are on rate to Complete Cerberus",
                    "Level 75: You had a 50% chance to obtain a Jar of souls",
                    "Level 79: You are on rate to obtain a Jar of souls",
                    "Level 79: You had a 50% chance to obtain Hellpuppy",
                    "Level 81: You had a 99% chance to obtain a Pegasian crystal",
                    "Level 81: You had a 99% chance to obtain a Primordial crystal",
                    "Level 81: You had a 99% chance to obtain an Eternal crystal",
                    "Level 81: You had a 99% chance to obtain Smouldering stone",
                    "Level 83: You are on rate to obtain Hellpuppy",
                    "Level 83: You had a 50% chance to Green Log Cerberus",
                    "Level 83: You had a 99% chance to Complete Cerberus",
                    "Level 86: You are on rate to Green Log Cerberus",
                    "Level 94: You had a 99% chance to obtain a Jar of souls",
                    "Level 98: You had a 99% chance to obtain Hellpuppy",
                    "Level 99: You had a 99% chance to Green Log Cerberus"
            )
    ),
    CHAOS_ELEMENTAL(
            "Chaos Elemental",
            "chaos_elemental",
            8777,
            "game_icon_chaoselemental.png",
            List.of(
                    "Level 77: You had a 50% chance to Complete Chaos Elemental",
                    "Level 77: You had a 50% chance to obtain a Dragon Pickaxe",
                    "Level 79: You had a 50% chance to obtain Pet chaos elemental",
                    "Level 81: You are on rate to Complete Chaos Elemental",
                    "Level 81: You are on rate to obtain a Dragon Pickaxe",
                    "Level 82: You are on rate to obtain Pet chaos elemental",
                    "Level 84: You had a 50% chance to Green Log Chaos Elemental",
                    "Level 86: You are on rate to Green Log Chaos Elemental",
                    "Level 96: You had a 99% chance to Complete Chaos Elemental",
                    "Level 96: You had a 99% chance to obtain a Dragon Pickaxe",
                    "Level 98: You had a 99% chance to obtain Pet chaos elemental",
                    "Level 99: You had a 99% chance to Green Log Chaos Elemental"
            )
    ),
    CHAOS_FANATIC(
            "Chaos Fanatic",
            "chaos_fanatic",
            2831,
            "game_icon_chaosfanatic.png",
            List.of(
                    "Level 66: You had a 50% chance to obtain Malediction shard 1",
                    "Level 66: You had a 50% chance to obtain Odium shard 1",
                    "Level 69: You are on rate to obtain Malediction shard 1",
                    "Level 69: You are on rate to obtain Odium shard 1",
                    "Level 71: You had a 50% chance to Complete Chaos Elemental",
                    "Level 74: You are on rate to Complete Chaos Elemental",
                    "Level 79: You had a 50% chance to obtain Pet chaos elemental",
                    "Level 81: You had a 50% chance to Green Log Chaos Elemental",
                    "Level 83: You are on rate to obtain Pet chaos elemental",
                    "Level 84: You are on rate to Green Log Chaos Elemental",
                    "Level 85: You had a 99% chance to obtain Malediction shard 1",
                    "Level 85: You had a 99% chance to obtain Odium shard 1",
                    "Level 86: You had a 99% chance to Complete Chaos Elemental",
                    "Level 98: You had a 99% chance to obtain Pet chaos elemental",
                    "Level 99: You had a 99% chance to Green Log Chaos Elemental"
            )
    ),
    COMMANDER_ZILYANA(
            "Commander Zilyana",
            "commander_zilyana",
            566,
            "game_icon_commanderzilyana.png",
            List.of(
                    "Level 42: You had a 50% chance to obtain the Saradomin sword",
                    "Level 46: You are on rate to obtain the Saradomin sword",
                    "Level 49: You had a 50% chance to obtain Saradomin's light",
                    "Level 53: You are on rate to obtain Saradomin's light",
                    "Level 56: You had a 50% chance to obtain the Armadyl crossbow",
                    "Level 56: You had a 50% chance to obtain the Saradomin hilt",
                    "Level 60: You are on rate to obtain the Armadyl crossbow",
                    "Level 60: You are on rate to obtain the Saradomin hilt",
                    "Level 60: You had a 50% chance to obtain a Godsword shard 1",
                    "Level 60: You had a 50% chance to obtain a Godsword shard 2",
                    "Level 60: You had a 50% chance to obtain a Godsword shard 3",
                    "Level 61: You had a 99% chance to obtain the Saradomin sword",
                    "Level 64: You are on rate to obtain a Godsword shard 1",
                    "Level 64: You are on rate to obtain a Godsword shard 2",
                    "Level 64: You are on rate to obtain a Godsword shard 3",
                    "Level 68: You had a 99% chance to obtain Saradomin's light",
                    "Level 70: You had a 50% chance to Complete Commander Zilyana",
                    "Level 72: You are on rate to Complete Commander Zilyana",
                    "Level 75: You had a 99% chance to obtain the Armadyl crossbow",
                    "Level 75: You had a 99% chance to obtain the Saradomin hilt",
                    "Level 79: You had a 50% chance to obtain Pet zilyana",
                    "Level 79: You had a 99% chance to obtain a Godsword shard 1",
                    "Level 79: You had a 99% chance to obtain a Godsword shard 2",
                    "Level 79: You had a 99% chance to obtain a Godsword shard 3",
                    "Level 80: You had a 50% chance to Green Log Commander Zilyana",
                    "Level 82: You had a 99% chance to Complete Commander Zilyana",
                    "Level 83: You are on rate to Green Log Commander Zilyana",
                    "Level 83: You are on rate to obtain Pet zilyana",
                    "Level 98: You had a 99% chance to obtain Pet zilyana",
                    "Level 99: You had a 99% chance to Green Log Commander Zilyana"
            )
    ),
    GENERAL_GRAARDOR(
            "General Graardor",
            "general_graardor",
            566,
            "game_icon_generalgraardor.png",
            List.of(
                    "Level 53: You had a 50% chance to obtain Bandos boots",
                    "Level 53: You had a 50% chance to obtain Bandos chestplate",
                    "Level 53: You had a 50% chance to obtain Bandos tassets",
                    "Level 56: You had a 50% chance to obtain Bandos hilt",
                    "Level 57: You are on rate to obtain Bandos boots",
                    "Level 57: You are on rate to obtain Bandos chestplate",
                    "Level 57: You are on rate to obtain Bandos tassets",
                    "Level 60: You are on rate to obtain Bandos hilt",
                    "Level 60: You had a 50% chance to obtain Godsword shard 1",
                    "Level 60: You had a 50% chance to obtain Godsword shard 2",
                    "Level 60: You had a 50% chance to obtain Godsword shard 3",
                    "Level 64: You are on rate to obtain Godsword shard 1",
                    "Level 64: You are on rate to obtain Godsword shard 2",
                    "Level 64: You are on rate to obtain Godsword shard 3",
                    "Level 70: You had a 50% chance to Complete General Graardor",
                    "Level 72: You are on rate to Complete General Graardor",
                    "Level 72: You had a 99% chance to obtain Bandos boots",
                    "Level 72: You had a 99% chance to obtain Bandos chestplate",
                    "Level 72: You had a 99% chance to obtain Bandos tassets",
                    "Level 75: You had a 99% chance to obtain Bandos hilt",
                    "Level 79: You had a 50% chance to obtain Pet general graardor",
                    "Level 79: You had a 99% chance to obtain Godsword shard 1",
                    "Level 79: You had a 99% chance to obtain Godsword shard 2",
                    "Level 79: You had a 99% chance to obtain Godsword shard 3",
                    "Level 80: You had a 50% chance to Green Log General Graardor",
                    "Level 82: You had a 99% chance to Complete General Graardor",
                    "Level 83: You are on rate to Green Log General Graardor",
                    "Level 83: You are on rate to obtain Pet general graardor",
                    "Level 98: You had a 99% chance to obtain Pet general graardor",
                    "Level 99: You had a 99% chance to Green Log General Graardor"
            )
    ),
    KREE_ARRA(
            "Kree'arra",
            "kree_arra",
            566,
            "game_icon_kreearra.png",
            List.of(
                    "Level 53: You had a 50% chance to obtain Armadyl chainskirt",
                    "Level 53: You had a 50% chance to obtain Armadyl chestplate",
                    "Level 53: You had a 50% chance to obtain Armadyl helmet",
                    "Level 56: You had a 50% chance to obtain Armadyl hilt",
                    "Level 57: You are on rate to obtain Armadyl chainskirt",
                    "Level 57: You are on rate to obtain Armadyl chestplate",
                    "Level 57: You are on rate to obtain Armadyl helmet",
                    "Level 60: You are on rate to obtain Armadyl hilt",
                    "Level 60: You had a 50% chance to obtain Godsword shard 1",
                    "Level 60: You had a 50% chance to obtain Godsword shard 2",
                    "Level 60: You had a 50% chance to obtain Godsword shard 3",
                    "Level 64: You are on rate to obtain Godsword shard 1",
                    "Level 64: You are on rate to obtain Godsword shard 2",
                    "Level 64: You are on rate to obtain Godsword shard 3",
                    "Level 70: You had a 50% chance to Complete Kree'arra",
                    "Level 72: You are on rate to Complete Kree'arra",
                    "Level 72: You had a 99% chance to obtain Armadyl chainskirt",
                    "Level 72: You had a 99% chance to obtain Armadyl chestplate",
                    "Level 72: You had a 99% chance to obtain Armadyl helmet",
                    "Level 75: You had a 99% chance to obtain Armadyl hilt",
                    "Level 79: You had a 50% chance to obtain Pet kree'arra",
                    "Level 79: You had a 99% chance to obtain Godsword shard 1",
                    "Level 79: You had a 99% chance to obtain Godsword shard 2",
                    "Level 79: You had a 99% chance to obtain Godsword shard 3",
                    "Level 80: You had a 50% chance to Green Log Kree'arra",
                    "Level 82: You had a 99% chance to Complete Kree'arra",
                    "Level 83: You are on rate to Green Log Kree'arra",
                    "Level 83: You are on rate to obtain Pet kree'arra",
                    "Level 98: You had a 99% chance to obtain Pet kree'arra",
                    "Level 99: You had a 99% chance to Green Log Kree'arra"
            )
    ),
    K_RIL_TSUTSAROTH(
            "K'ril Tsutsaroth",
            "k_ril_tsutsaroth",
            566,
            "game_icon_kriltsutsaroth.png",
            List.of(
                    "Level 42: You had a 50% chance to obtain Steam battlestaff",
                    "Level 42: You had a 50% chance to obtain Zamorakian spear",
                    "Level 46: You are on rate to obtain Steam battlestaff",
                    "Level 46: You are on rate to obtain Zamorakian spear",
                    "Level 56: You had a 50% chance to obtain Staff of the dead",
                    "Level 56: You had a 50% chance to obtain Zamorak hilt",
                    "Level 60: You are on rate to obtain Staff of the dead",
                    "Level 60: You are on rate to obtain Zamorak hilt",
                    "Level 60: You had a 50% chance to obtain Godsword shard 1",
                    "Level 60: You had a 50% chance to obtain Godsword shard 2",
                    "Level 60: You had a 50% chance to obtain Godsword shard 3",
                    "Level 61: You had a 99% chance to obtain Steam battlestaff",
                    "Level 61: You had a 99% chance to obtain Zamorakian spear",
                    "Level 64: You are on rate to obtain Godsword shard 1",
                    "Level 64: You are on rate to obtain Godsword shard 2",
                    "Level 64: You are on rate to obtain Godsword shard 3",
                    "Level 70: You had a 50% chance to Complete K'ril Tsutsaroth",
                    "Level 72: You are on rate to Complete K'ril Tsutsaroth",
                    "Level 75: You had a 99% chance to obtain Staff of the dead",
                    "Level 75: You had a 99% chance to obtain Zamorak hilt",
                    "Level 79: You had a 50% chance to obtain Pet k'ril tsutsaroth",
                    "Level 79: You had a 99% chance to obtain Godsword shard 1",
                    "Level 79: You had a 99% chance to obtain Godsword shard 2",
                    "Level 79: You had a 99% chance to obtain Godsword shard 3",
                    "Level 80: You had a 50% chance to Green Log K'ril Tsutsaroth",
                    "Level 82: You had a 99% chance to Complete K'ril Tsutsaroth",
                    "Level 83: You are on rate to Green Log K'ril Tsutsaroth",
                    "Level 83: You are on rate to obtain Pet k'ril tsutsaroth",
                    "Level 98: You had a 99% chance to obtain Pet k'ril tsutsaroth",
                    "Level 99: You had a 99% chance to Green Log K'ril Tsutsaroth"
            )
    ),
    NEX(
            "Nex",
            "nex",
            2778,
            "game_icon_nex.png",
            List.of(
                    "Level 72: You had a 50% chance to obtain Nexling",
                    "Level 73: You had a 50% chance to obtain Zaryte vambraces",
                    "Level 76: You are on rate to obtain Nexling",
                    "Level 76: You are on rate to obtain Zaryte vambraces",
                    "Level 77: You had a 50% chance to obtain Nihil horn",
                    "Level 77: You had a 50% chance to obtain Torva full helm (damaged)",
                    "Level 77: You had a 50% chance to obtain Torva platebody (damaged)",
                    "Level 77: You had a 50% chance to obtain Torva platelegs (damaged)",
                    "Level 81: You are on rate to obtain Nihil horn",
                    "Level 81: You are on rate to obtain Torva full helm (damaged)",
                    "Level 81: You are on rate to obtain Torva platebody (damaged)",
                    "Level 81: You are on rate to obtain Torva platelegs (damaged)",
                    "Level 87: You had a 50% chance to Complete Nex",
                    "Level 87: You had a 50% chance to Green Log Nex",
                    "Level 89: You are on rate to Complete Nex",
                    "Level 89: You are on rate to Green Log Nex",
                    "Level 91: You had a 99% chance to obtain Nexling",
                    "Level 92: You had a 99% chance to obtain Zaryte vambraces",
                    "Level 96: You had a 99% chance to obtain Nihil horn",
                    "Level 96: You had a 99% chance to obtain Torva full helm (damaged)",
                    "Level 96: You had a 99% chance to obtain Torva platebody (damaged)",
                    "Level 96: You had a 99% chance to obtain Torva platelegs (damaged)",
                    "Level 98: You had a 99% chance to Complete Nex",
                    "Level 99: You had a 99% chance to Green Log Nex"
            )
    ),
    GIANT_MOLE(
            "Giant Mole",
            "giant_mole",
            943,
            "game_icon_giantmole.png",
            List.of(
                    "Level 79: You had a 50% chance to Green Log Giant Mole",
                    "Level 83: You are on rate to Green Log Giant Mole",
                    "Level 99: You had a 99% chance to Green Log Giant Mole"
            )
    ),
    CORPOREAL_BEAST(
            "Corporeal Beast",
            "corporeal_beast",
            532,
            "game_icon_corporealbeast.png",
            List.of(
                    "Level 35: You had a 50% chance to obtain Spirit shield",
                    "Level 39: You are on rate to obtain Spirit shield",
                    "Level 45: You had a 50% chance to obtain Holy elixir",
                    "Level 48: You are on rate to obtain Holy elixir",
                    "Level 54: You had a 99% chance to obtain Spirit shield",
                    "Level 63: You had a 50% chance to obtain Jar of spirits",
                    "Level 64: You had a 99% chance to obtain Holy elixir",
                    "Level 66: You are on rate to obtain Jar of spirits",
                    "Level 66: You had a 50% chance to obtain Arcane sigil",
                    "Level 66: You had a 50% chance to obtain Spectral sigil",
                    "Level 69: You are on rate to obtain Arcane sigil",
                    "Level 69: You are on rate to obtain Spectral sigil",
                    "Level 77: You had a 50% chance to obtain Elysian sigil",
                    "Level 79: You had a 50% chance to Complete Corporeal Beast",
                    "Level 79: You had a 50% chance to obtain Pet dark core",
                    "Level 81: You are on rate to obtain Elysian sigil",
                    "Level 82: You are on rate to Complete Corporeal Beast",
                    "Level 82: You had a 99% chance to obtain Jar of spirits",
                    "Level 83: You are on rate to obtain Pet dark core",
                    "Level 84: You had a 50% chance to Green Log Corporeal Beast",
                    "Level 85: You had a 99% chance to obtain Arcane sigil",
                    "Level 85: You had a 99% chance to obtain Spectral sigil",
                    "Level 86: You are on rate to Green Log Corporeal Beast",
                    "Level 96: You had a 99% chance to Complete Corporeal Beast",
                    "Level 96: You had a 99% chance to obtain Elysian sigil",
                    "Level 98: You had a 99% chance to obtain Pet dark core",
                    "Level 99: You had a 99% chance to Green Log Corporeal Beast"
            )
    ),
    CRAZY_ARCHAEOLOGIST(
            "Crazy Archaeologist",
            "crazy_archaeologist",
            9626,
            "game_icon_crazyarchaeologist.png",
            List.of(
                    "Level 71: You had a 50% chance to obtain Fedora",
                    "Level 75: You are on rate to obtain Fedora",
                    "Level 78: You had a 50% chance to obtain Malediction shard 2",
                    "Level 78: You had a 50% chance to obtain Odium shard 2",
                    "Level 82: You are on rate to obtain Malediction shard 2",
                    "Level 82: You are on rate to obtain Odium shard 2",
                    "Level 84: You had a 50% chance to Green Log Crazy Archaeologist",
                    "Level 87: You are on rate to Green Log Crazy Archaeologist",
                    "Level 90: You had a 99% chance to obtain Fedora",
                    "Level 97: You had a 99% chance to obtain Malediction shard 2",
                    "Level 97: You had a 99% chance to obtain Odium shard 2",
                    "Level 99: You had a 99% chance to Green Log Crazy Archaeologist"
            )
    ),
    DAGANNOTH_PRIME(
            "Dagannoth Prime",
            "dagannoth_prime",
            566,
            "game_icon_dagannothprime.png",
            List.of(
                    "Level 43: You had a 50% chance to obtain Dragon axe",
                    "Level 43: You had a 50% chance to obtain Mud battlestaff",
                    "Level 43: You had a 50% chance to obtain Seers ring",
                    "Level 46: You are on rate to obtain Dragon axe",
                    "Level 46: You are on rate to obtain Mud battlestaff",
                    "Level 46: You are on rate to obtain Seers ring",
                    "Level 51: You had a 50% chance to Complete Dagannoth Prime",
                    "Level 53: You are on rate to Complete Dagannoth Prime",
                    "Level 61: You had a 99% chance to obtain Dragon axe",
                    "Level 61: You had a 99% chance to obtain Mud battlestaff",
                    "Level 61: You had a 99% chance to obtain Seers ring",
                    "Level 64: You had a 99% chance to Complete Dagannoth Prime",
                    "Level 79: You had a 50% chance to Green Log Dagannoth Prime",
                    "Level 79: You had a 50% chance to obtain Pet dagannoth prime",
                    "Level 83: You are on rate to Green Log Dagannoth Prime",
                    "Level 83: You are on rate to obtain Pet dagannoth prime",
                    "Level 98: You had a 99% chance to obtain Pet dagannoth prime",
                    "Level 99: You had a 99% chance to Green Log Dagannoth Prime"
            )
    ),
    DAGANNOTH_REX(
            "Dagannoth Rex",
            "dagannoth_rex",
            566,
            "game_icon_dagannothrex.png",
            List.of(
                    "Level 43: You had a 50% chance to obtain Berserker ring",
                    "Level 43: You had a 50% chance to obtain Dragon axe",
                    "Level 43: You had a 50% chance to obtain Warrior ring",
                    "Level 46: You are on rate to obtain Berserker ring",
                    "Level 46: You are on rate to obtain Dragon axe",
                    "Level 46: You are on rate to obtain Warrior ring",
                    "Level 51: You had a 50% chance to Complete Dagannoth Rex",
                    "Level 53: You are on rate to Complete Dagannoth Rex",
                    "Level 61: You had a 99% chance to obtain Berserker ring",
                    "Level 61: You had a 99% chance to obtain Dragon axe",
                    "Level 61: You had a 99% chance to obtain Warrior ring",
                    "Level 64: You had a 99% chance to Complete Dagannoth Rex",
                    "Level 79: You had a 50% chance to Green Log Dagannoth Rex",
                    "Level 79: You had a 50% chance to obtain Pet dagannoth rex",
                    "Level 83: You are on rate to Green Log Dagannoth Rex",
                    "Level 83: You are on rate to obtain Pet dagannoth rex",
                    "Level 98: You had a 99% chance to obtain Pet dagannoth rex",
                    "Level 99: You had a 99% chance to Green Log Dagannoth Rex"
            )
    ),
    DAGANNOTH_SUPREME(
            "Dagannoth Supreme",
            "dagannoth_supreme",
            566,
            "game_icon_dagannothsupreme.png",
            List.of(
                    "Level 43: You had a 50% chance to obtain Archers ring",
                    "Level 43: You had a 50% chance to obtain Dragon axe",
                    "Level 43: You had a 50% chance to obtain Seercull",
                    "Level 46: You are on rate to obtain Archers ring",
                    "Level 46: You are on rate to obtain Dragon axe",
                    "Level 46: You are on rate to obtain Seercull",
                    "Level 51: You had a 50% chance to Complete Dagannoth Supreme",
                    "Level 53: You are on rate to Complete Dagannoth Supreme",
                    "Level 61: You had a 99% chance to obtain Archers ring",
                    "Level 61: You had a 99% chance to obtain Dragon axe",
                    "Level 61: You had a 99% chance to obtain Seercull",
                    "Level 64: You had a 99% chance to Complete Dagannoth Supreme",
                    "Level 79: You had a 50% chance to Green Log Dagannoth Supreme",
                    "Level 79: You had a 50% chance to obtain Pet dagannoth supreme",
                    "Level 83: You are on rate to Green Log Dagannoth Supreme",
                    "Level 83: You are on rate to obtain Pet dagannoth supreme",
                    "Level 98: You had a 99% chance to obtain Pet dagannoth supreme",
                    "Level 99: You had a 99% chance to Green Log Dagannoth Supreme"
            )
    ),
    DERANGED_ARCHAEOLOGIST(
            "Deranged Archaeologist",
            "deranged_archaeologist",
            65499,
            "game_icon_derangedarchaeologist.png",
            List.of(
                    "Level 79: You had a 50% chance to Green Log Deranged archaeologist",
                    "Level 79: You had a 50% chance to obtain Steel ring",
                    "Level 83: You are on rate to Green Log Deranged archaeologist",
                    "Level 83: You are on rate to obtain Steel ring",
                    "Level 99: You had a 99% chance to obtain Steel ring",
                    "Level 99: You had a 99% chance to Green Log Deranged archaeologist"
            )
    ),
    DUKE_SUCELLUS(
            "Duke Sucellus",
            "duke_sucellus",
            961,
            "game_icon_dukesucellus.png",
            List.of(
                    "Level 54: You had a 50% chance to obtain Chromium ingot",
                    "Level 58: You are on rate to obtain Chromium ingot",
                    "Level 65: You had a 50% chance to obtain Eye of the duke",
                    "Level 68: You had a 50% chance to obtain Magus vestige",
                    "Level 69: You are on rate to obtain Eye of the duke",
                    "Level 70: You are on rate to obtain Magus vestige",
                    "Level 73: You had a 99% chance to obtain Chromium ingot",
                    "Level 76: You had a 50% chance to obtain Virtus mask",
                    "Level 76: You had a 50% chance to obtain Virtus robe bottom",
                    "Level 76: You had a 50% chance to obtain Virtus robe top",
                    "Level 78: You had a 50% chance to obtain Baron",
                    "Level 79: You had a 99% chance to obtain Magus vestige",
                    "Level 80: You are on rate to obtain Virtus mask",
                    "Level 80: You are on rate to obtain Virtus robe bottom",
                    "Level 80: You are on rate to obtain Virtus robe top",
                    "Level 82: You are on rate to obtain Baron",
                    "Level 84: You had a 99% chance to obtain Eye of the duke",
                    "Level 85: You had a 50% chance to Complete Duke Sucellus",
                    "Level 87: You are on rate to Complete Duke Sucellus",
                    "Level 87: You had a 50% chance to Green Log Duke Sucellus",
                    "Level 88: You are on rate to Green Log Duke Sucellus",
                    "Level 95: You had a 99% chance to obtain Virtus mask",
                    "Level 95: You had a 99% chance to obtain Virtus robe bottom",
                    "Level 95: You had a 99% chance to obtain Virtus robe top",
                    "Level 97: You had a 99% chance to obtain Baron",
                    "Level 98: You had a 99% chance to Complete Duke Sucellus",
                    "Level 99: You had a 99% chance to Green Log Duke Sucellus"
            )
    ),
    THE_LEVIATHAN(
            "The Leviathan",
            "the_leviathan",
            922,
            "game_icon_theleviathan.png",
            List.of(
                    "Level 54: You had a 50% chance to obtain Chromium ingot",
                    "Level 58: You are on rate to obtain Chromium ingot",
                    "Level 65: You had a 50% chance to obtain Leviathan's lure",
                    "Level 68: You had a 50% chance to obtain Venator vestige",
                    "Level 69: You are on rate to obtain Leviathan's lure",
                    "Level 70: You are on rate to obtain Venator vestige",
                    "Level 73: You had a 99% chance to obtain Chromium ingot",
                    "Level 76: You had a 50% chance to obtain Virtus mask",
                    "Level 76: You had a 50% chance to obtain Virtus robe bottom",
                    "Level 76: You had a 50% chance to obtain Virtus robe top",
                    "Level 77: You had a 50% chance to obtain Lil'viathan",
                    "Level 79: You had a 99% chance to obtain Venator vestige",
                    "Level 80: You are on rate to obtain Virtus mask",
                    "Level 80: You are on rate to obtain Virtus robe bottom",
                    "Level 80: You are on rate to obtain Virtus robe top",
                    "Level 81: You are on rate to obtain Lil'viathan",
                    "Level 85: You had a 50% chance to Complete The Leviathan",
                    "Level 85: You had a 99% chance to obtain Leviathan's lure",
                    "Level 87: You are on rate to Complete The Leviathan",
                    "Level 87: You had a 50% chance to Green Log The Leviathan",
                    "Level 89: You are on rate to Green Log The Leviathan",
                    "Level 96: You had a 99% chance to obtain Lil'viathan",
                    "Level 96: You had a 99% chance to obtain Virtus mask",
                    "Level 96: You had a 99% chance to obtain Virtus robe bottom",
                    "Level 96: You had a 99% chance to obtain Virtus robe top",
                    "Level 98: You had a 99% chance to Complete The Leviathan",
                    "Level 99: You had a 99% chance to Green Log The Leviathan"
            )
    ),
    VARDORVIS(
            "Vardorvis",
            "vardorvis",
            679,
            "game_icon_vardorvis.png",
            List.of(
                    "Level 55: You had a 50% chance to obtain Chromium ingot",
                    "Level 59: You are on rate to obtain Chromium ingot",
                    "Level 66: You had a 50% chance to obtain Executioner's axe head",
                    "Level 68: You had a 50% chance to obtain Ultor vestige",
                    "Level 70: You are on rate to obtain Executioner's axe head",
                    "Level 70: You are on rate to obtain Ultor vestige",
                    "Level 74: You had a 99% chance to obtain Chromium ingot",
                    "Level 76: You had a 50% chance to obtain Butch",
                    "Level 77: You had a 50% chance to obtain Virtus mask",
                    "Level 77: You had a 50% chance to obtain Virtus robe bottom",
                    "Level 77: You had a 50% chance to obtain Virtus robe top",
                    "Level 80: You are on rate to obtain Butch",
                    "Level 80: You had a 99% chance to obtain Ultor vestige",
                    "Level 81: You are on rate to obtain Virtus mask",
                    "Level 81: You are on rate to obtain Virtus robe bottom",
                    "Level 81: You are on rate to obtain Virtus robe top",
                    "Level 85: You had a 50% chance to Complete Vardorvis",
                    "Level 85: You had a 99% chance to obtain Executioner's axe head",
                    "Level 87: You are on rate to Complete Vardorvis",
                    "Level 87: You had a 50% chance to Green Log Vardorvis",
                    "Level 89: You are on rate to Green Log Vardorvis",
                    "Level 95: You had a 99% chance to obtain Butch",
                    "Level 96: You had a 99% chance to obtain Virtus mask",
                    "Level 96: You had a 99% chance to obtain Virtus robe bottom",
                    "Level 96: You had a 99% chance to obtain Virtus robe top",
                    "Level 98: You had a 99% chance to Complete Vardorvis",
                    "Level 99: You had a 99% chance to Green Log Vardorvis"
            )
    ),
    THE_WHISPERER(
            "The Whisperer",
            "the_whisperer",
            1278,
            "game_icon_thewhisperer.png",
            List.of(
                    "Level 53: You had a 50% chance to obtain Chromium ingot",
                    "Level 57: You are on rate to obtain Chromium ingot",
                    "Level 65: You had a 50% chance to obtain Siren's staff",
                    "Level 67: You had a 50% chance to obtain Bellator vestige",
                    "Level 68: You are on rate to obtain Siren's staff",
                    "Level 69: You are on rate to obtain Bellator vestige",
                    "Level 73: You had a 99% chance to obtain Chromium ingot",
                    "Level 76: You had a 50% chance to obtain Virtus mask",
                    "Level 76: You had a 50% chance to obtain Virtus robe bottom",
                    "Level 76: You had a 50% chance to obtain Virtus robe top",
                    "Level 78: You had a 50% chance to obtain Wisp",
                    "Level 79: You are on rate to obtain Virtus mask",
                    "Level 79: You are on rate to obtain Virtus robe bottom",
                    "Level 79: You are on rate to obtain Virtus robe top",
                    "Level 79: You had a 99% chance to obtain Bellator vestige",
                    "Level 82: You are on rate to obtain Wisp",
                    "Level 84: You had a 50% chance to Complete The Whisperer",
                    "Level 84: You had a 99% chance to obtain Siren's staff",
                    "Level 86: You are on rate to Complete The Whisperer",
                    "Level 86: You had a 50% chance to Green Log The Whisperer",
                    "Level 88: You are on rate to Green Log The Whisperer",
                    "Level 95: You had a 99% chance to obtain Virtus mask",
                    "Level 95: You had a 99% chance to obtain Virtus robe bottom",
                    "Level 95: You had a 99% chance to obtain Virtus robe top",
                    "Level 97: You had a 99% chance to Complete The Whisperer",
                    "Level 97: You had a 99% chance to obtain Wisp",
                    "Level 99: You had a 99% chance to Green Log The Whisperer"
            )
    ),
    GROTESQUE_GUARDIANS(
            "Grotesque Guardians",
            "grotesque_guardians",
            560,
            "game_icon_grotesqueguardians.png",
            List.of(
                    "Level 42: You had a 50% chance to obtain Granite maul",
                    "Level 46: You are on rate to obtain Granite maul",
                    "Level 49: You had a 50% chance to obtain Granite ring",
                    "Level 53: You are on rate to obtain Granite ring",
                    "Level 53: You had a 50% chance to obtain Granite hammer",
                    "Level 56: You had a 50% chance to obtain Black tourmaline core",
                    "Level 57: You are on rate to obtain Granite hammer",
                    "Level 60: You are on rate to obtain Black tourmaline core",
                    "Level 61: You had a 99% chance to obtain Granite maul",
                    "Level 63: You had a 50% chance to obtain Granite gloves",
                    "Level 65: You are on rate to obtain Granite gloves",
                    "Level 65: You had a 50% chance to Complete Grotesque Guardians",
                    "Level 67: You are on rate to Complete Grotesque Guardians",
                    "Level 68: You had a 99% chance to obtain Granite ring",
                    "Level 72: You had a 99% chance to obtain Granite hammer",
                    "Level 74: You had a 50% chance to obtain Noon",
                    "Level 74: You had a 99% chance to obtain Granite gloves",
                    "Level 75: You had a 99% chance to obtain Black tourmaline core",
                    "Level 76: You had a 99% chance to Complete Grotesque Guardians",
                    "Level 78: You are on rate to obtain Noon",
                    "Level 79: You had a 50% chance to obtain Jar of stone",
                    "Level 83: You are on rate to obtain Jar of stone",
                    "Level 83: You had a 50% chance to Green Log Grotesque Guardians",
                    "Level 85: You are on rate to Green Log Grotesque Guardians",
                    "Level 93: You had a 99% chance to obtain Noon",
                    "Level 98: You had a 99% chance to obtain Jar of stone",
                    "Level 99: You had a 99% chance to Green Log Grotesque Guardians"
            )
    ),
    HESPORI(
            "Hespori",
            "hespori",
            81977,
            "game_icon_hespori.png",
            List.of(
                    "Level 79: You had a 50% chance to Green Log Hespori",
                    "Level 79: You had a 50% chance to obtain Bottomless compost bucket",
                    "Level 83: You are on rate to Green Log Hespori",
                    "Level 83: You are on rate to obtain Bottomless compost bucket",
                    "Level 99: You had a 99% chance to obtain Bottomless compost bucket",
                    "Level 99: You had a 99% chance to Green Log Hespori"
            )
    ),
    KALPHITE_QUEEN(
            "Kalphite Queen",
            "kalphite_queen",
            925,
            "game_icon_kalphitequeen.png",
            List.of(
                    "Level 47: You had a 50% chance to obtain Dragon chainbody",
                    "Level 47: You had a 50% chance to obtain Kq head",
                    "Level 51: You are on rate to obtain Dragon chainbody",
                    "Level 51: You are on rate to obtain Kq head",
                    "Level 54: You had a 50% chance to obtain Dragon 2h sword",
                    "Level 58: You are on rate to obtain Dragon 2h sword",
                    "Level 59: You had a 50% chance to obtain Dragon pickaxe",
                    "Level 63: You are on rate to obtain Dragon pickaxe",
                    "Level 63: You had a 50% chance to Complete Kalphite Queen",
                    "Level 66: You are on rate to Complete Kalphite Queen",
                    "Level 66: You had a 99% chance to obtain Dragon chainbody",
                    "Level 66: You had a 99% chance to obtain Kq head",
                    "Level 73: You had a 99% chance to obtain Dragon 2h sword",
                    "Level 75: You had a 50% chance to obtain Jar of sand",
                    "Level 78: You had a 99% chance to Complete Kalphite Queen",
                    "Level 78: You had a 99% chance to obtain Dragon pickaxe",
                    "Level 79: You are on rate to obtain Jar of sand",
                    "Level 79: You had a 50% chance to obtain Kalphite princess",
                    "Level 83: You are on rate to obtain Kalphite princess",
                    "Level 83: You had a 50% chance to Green Log Kalphite Queen",
                    "Level 86: You are on rate to Green Log Kalphite Queen",
                    "Level 94: You had a 99% chance to obtain Jar of sand",
                    "Level 98: You had a 99% chance to obtain Kalphite princess",
                    "Level 99: You had a 99% chance to Green Log Kalphite Queen"
            )
    ),
    KING_BLACK_DRAGON(
            "King Black Dragon",
            "king_black_dragon",
            560,
            "game_icon_kingblackdragon.png",
            List.of(
                    "Level 42: You had a 50% chance to obtain Kbd heads",
                    "Level 46: You are on rate to obtain Kbd heads",
                    "Level 61: You had a 99% chance to obtain Kbd heads",
                    "Level 74: You had a 50% chance to obtain Prince black dragon",
                    "Level 78: You are on rate to obtain Prince black dragon",
                    "Level 79: You had a 50% chance to obtain Draconic visage",
                    "Level 80: You had a 50% chance to Complete King Black Dragon",
                    "Level 83: You are on rate to Complete King Black Dragon",
                    "Level 83: You are on rate to obtain Draconic visage",
                    "Level 83: You had a 50% chance to Green Log King Black Dragon",
                    "Level 85: You are on rate to Green Log King Black Dragon",
                    "Level 93: You had a 99% chance to obtain Prince black dragon",
                    "Level 98: You had a 99% chance to Complete King Black Dragon",
                    "Level 98: You had a 99% chance to obtain Draconic visage",
                    "Level 99: You had a 99% chance to Green Log King Black Dragon"
            )
    ),
    KRAKEN(
            "Kraken",
            "kraken",
            943,
            "game_icon_kraken.png",
            List.of(
                    "Level 62: You had a 50% chance to Complete Kraken",
                    "Level 62: You had a 50% chance to obtain Trident of the seas (full)",
                    "Level 65: You are on rate to Complete Kraken",
                    "Level 65: You are on rate to obtain Trident of the seas (full)",
                    "Level 68: You had a 50% chance to obtain Jar of dirt",
                    "Level 72: You are on rate to obtain Jar of dirt",
                    "Level 79: You had a 50% chance to obtain Pet kraken",
                    "Level 81: You had a 50% chance to Green Log Kraken",
                    "Level 81: You had a 99% chance to Complete Kraken",
                    "Level 81: You had a 99% chance to obtain Trident of the seas (full)",
                    "Level 83: You are on rate to obtain Pet kraken",
                    "Level 84: You are on rate to Green Log Kraken",
                    "Level 87: You had a 99% chance to obtain Jar of dirt",
                    "Level 98: You had a 99% chance to obtain Pet kraken",
                    "Level 99: You had a 99% chance to Green Log Kraken"
            )
    ),



    THE_NIGHTMARE(
            "The Nightmare",
            "the_nightmare",
            706,
            "game_icon_nightmare.png",
            List.of(
                    "Level 53: You had a 50% chance to obtain Nightmare staff",
                    "Level 57: You are on rate to obtain Nightmare staff",
                    "Level 57: You had a 50% chance to obtain Inquisitor's great helm",
                    "Level 57: You had a 50% chance to obtain Inquisitor's hauberk",
                    "Level 57: You had a 50% chance to obtain Inquisitor's plateskirt",
                    "Level 60: You are on rate to obtain Inquisitor's great helm",
                    "Level 60: You are on rate to obtain Inquisitor's hauberk",
                    "Level 60: You are on rate to obtain Inquisitor's plateskirt",
                    "Level 62: You had a 50% chance to obtain Inquisitor's mace",
                    "Level 65: You had a 50% chance to obtain Eldritch orb",
                    "Level 65: You had a 50% chance to obtain Harmonised orb",
                    "Level 65: You had a 50% chance to obtain Volatile orb",
                    "Level 66: You are on rate to obtain Inquisitor's mace",
                    "Level 69: You are on rate to obtain Eldritch orb",
                    "Level 69: You are on rate to obtain Harmonised orb",
                    "Level 69: You are on rate to obtain Volatile orb",
                    "Level 72: You had a 50% chance to obtain Jar of dreams",
                    "Level 72: You had a 99% chance to obtain Nightmare staff",
                    "Level 75: You had a 50% chance to Complete The Nightmare",
                    "Level 76: You are on rate to Complete The Nightmare",
                    "Level 76: You are on rate to obtain Jar of dreams",
                    "Level 76: You had a 99% chance to obtain Inquisitor's great helm",
                    "Level 76: You had a 99% chance to obtain Inquisitor's hauberk",
                    "Level 76: You had a 99% chance to obtain Inquisitor's plateskirt",
                    "Level 79: You had a 50% chance to obtain Little nightmare",
                    "Level 82: You had a 99% chance to obtain Inquisitor's mace",
                    "Level 83: You are on rate to obtain Little nightmare",
                    "Level 83: You had a 50% chance to Green Log The Nightmare",
                    "Level 84: You had a 99% chance to obtain Eldritch orb",
                    "Level 84: You had a 99% chance to obtain Harmonised orb",
                    "Level 84: You had a 99% chance to obtain Volatile orb",
                    "Level 85: You are on rate to Green Log The Nightmare",
                    "Level 86: You had a 99% chance to Complete The Nightmare",
                    "Level 91: You had a 99% chance to obtain Jar of dreams",
                    "Level 98: You had a 99% chance to obtain Little nightmare",
                    "Level 99: You had a 99% chance to Green Log The Nightmare"
            )
    ),
    PHOSANIS_NIGHTMARE(
            "Phosani's Nightmare",
            "phosanis_nightmare",
            707,
            "game_icon_phosanisnightmare.png",
            List.of(
                    "Level 59: You had a 50% chance to obtain Nightmare staff",
                    "Level 62: You had a 50% chance to obtain Inquisitor's great helm",
                    "Level 62: You had a 50% chance to obtain Inquisitor's hauberk",
                    "Level 62: You had a 50% chance to obtain Inquisitor's plateskirt",
                    "Level 63: You are on rate to obtain Nightmare staff",
                    "Level 66: You are on rate to obtain Inquisitor's great helm",
                    "Level 66: You are on rate to obtain Inquisitor's hauberk",
                    "Level 66: You are on rate to obtain Inquisitor's plateskirt",
                    "Level 68: You had a 50% chance to obtain Inquisitor's mace",
                    "Level 69: You had a 50% chance to obtain Little nightmare",
                    "Level 70: You had a 50% chance to obtain Eldritch orb",
                    "Level 70: You had a 50% chance to obtain Harmonised orb",
                    "Level 70: You had a 50% chance to obtain Volatile orb",
                    "Level 71: You are on rate to obtain Inquisitor's mace",
                    "Level 73: You are on rate to obtain Little nightmare",
                    "Level 74: You are on rate to obtain Eldritch orb",
                    "Level 74: You are on rate to obtain Harmonised orb",
                    "Level 74: You are on rate to obtain Volatile orb",
                    "Level 78: You had a 99% chance to obtain Nightmare staff",
                    "Level 79: You had a 50% chance to obtain Jar of dreams",
                    "Level 80: You had a 50% chance to Complete Phosani's Nightmare",
                    "Level 81: You had a 99% chance to obtain Inquisitor's great helm",
                    "Level 81: You had a 99% chance to obtain Inquisitor's hauberk",
                    "Level 81: You had a 99% chance to obtain Inquisitor's plateskirt",
                    "Level 82: You are on rate to Complete Phosani's Nightmare",
                    "Level 83: You are on rate to obtain Jar of dreams",
                    "Level 84: You had a 50% chance to Green Log Phosani's Nightmare",
                    "Level 86: You are on rate to Green Log Phosani's Nightmare",
                    "Level 87: You had a 99% chance to obtain Inquisitor's mace",
                    "Level 88: You had a 99% chance to obtain Little nightmare",
                    "Level 89: You had a 99% chance to obtain Eldritch orb",
                    "Level 89: You had a 99% chance to obtain Harmonised orb",
                    "Level 89: You had a 99% chance to obtain Volatile orb",
                    "Level 92: You had a 99% chance to Complete Phosani's Nightmare",
                    "Level 98: You had a 99% chance to obtain Jar of dreams",
                    "Level 99: You had a 99% chance to Green Log Phosani's Nightmare"
            )
    ),
    OBOR(
            "Obor",
            "obor",
            1594,
            "game_icon_obor.png",
            List.of(
                    "Level 79: You had a 50% chance to Green Log Obor",
                    "Level 79: You had a 50% chance to obtain Hill giant club",
                    "Level 83: You are on rate to Green Log Obor",
                    "Level 83: You are on rate to obtain Hill giant club",
                    "Level 98: You had a 99% chance to obtain Hill giant club",
                    "Level 99: You had a 99% chance to Green Log Obor"
            )
    ),
    PHANTOM_MUSPAH(
            "Phantom Muspah",
            "phantom_muspah",
            1132,
            "game_icon_phantommuspah.png",
            List.of(    "Level 40: You had a 50% chance to obtain Ancient icon",
                    "Level 44: You are on rate to obtain Ancient icon",
                    "Level 47: You had a 50% chance to obtain Venator shard",
                    "Level 51: You are on rate to obtain Venator shard",
                    "Level 59: You had a 99% chance to obtain Ancient icon",
                    "Level 66: You had a 50% chance to Complete Phantom Muspah",
                    "Level 66: You had a 99% chance to obtain Venator shard",
                    "Level 68: You are on rate to Complete Phantom Muspah",
                    "Level 75: You had a 99% chance to Complete Phantom Muspah",
                    "Level 79: You had a 50% chance to Green Log Phantom Muspah",
                    "Level 79: You had a 50% chance to obtain Muphin",
                    "Level 83: You are on rate to Green Log Phantom Muspah",
                    "Level 83: You are on rate to obtain Muphin",
                    "Level 98: You had a 99% chance to obtain Muphin",
                    "Level 99: You had a 99% chance to Green Log Phantom Muspah"
            )
    ),
    SARACHNIS(
            "Sarachnis",
            "sarachnis",
            925,
            "game_icon_sarachnis.png",
            List.of(
                    "Level 58: You had a 50% chance to Complete Sarachnis",
                    "Level 58: You had a 50% chance to obtain Sarachnis cudgel",
                    "Level 62: You are on rate to Complete Sarachnis",
                    "Level 62: You are on rate to obtain Sarachnis cudgel",
                    "Level 75: You had a 50% chance to obtain Jar of eyes",
                    "Level 78: You had a 99% chance to Complete Sarachnis",
                    "Level 78: You had a 99% chance to obtain Sarachnis cudgel",
                    "Level 79: You are on rate to obtain Jar of eyes",
                    "Level 79: You had a 50% chance to obtain Sraracha",
                    "Level 83: You are on rate to obtain Sraracha",
                    "Level 83: You had a 50% chance to Green Log Sarachnis",
                    "Level 86: You are on rate to Green Log Sarachnis",
                    "Level 94: You had a 99% chance to obtain Jar of eyes",
                    "Level 98: You had a 99% chance to obtain Sraracha",
                    "Level 99: You had a 99% chance to Green Log Sarachnis"
            )
    ),
    SCORPIA(
            "Scorpia",
            "scorpia",
            1404,
            "game_icon_scorpia.png",
            List.of(
                    "Level 52: You had a 50% chance to obtain Dragon 2h sword",
                    "Level 55: You are on rate to obtain Dragon 2h sword",
                    "Level 59: You had a 50% chance to obtain Malediction shard 3",
                    "Level 59: You had a 50% chance to obtain Odium shard 3",
                    "Level 62: You are on rate to obtain Malediction shard 3",
                    "Level 62: You are on rate to obtain Odium shard 3",
                    "Level 65: You had a 50% chance to Complete Scorpia",
                    "Level 67: You are on rate to Complete Scorpia",
                    "Level 71: You had a 99% chance to obtain Dragon 2h sword",
                    "Level 78: You had a 99% chance to obtain Malediction shard 3",
                    "Level 78: You had a 99% chance to obtain Odium shard 3",
                    "Level 79: You had a 50% chance to Green Log Scorpia",
                    "Level 79: You had a 50% chance to obtain Scorpia's offspring",
                    "Level 79: You had a 99% chance to Complete Scorpia",
                    "Level 83: You are on rate to Green Log Scorpia",
                    "Level 83: You are on rate to obtain Scorpia's offspring",
                    "Level 98: You had a 99% chance to obtain Scorpia's offspring",
                    "Level 99: You had a 99% chance to Green Log Scorpia"
            )
    ),
    SKOTIZO(
            "Skotizo",
            "skotizo",
            13970,
            "game_icon_skotizo.png",
            List.of(
                    "Level 58: You had a 50% chance to Complete Skotizo",
                    "Level 58: You had a 50% chance to obtain Dark claw",
                    "Level 62: You are on rate to Complete Skotizo",
                    "Level 62: You are on rate to obtain Dark claw",
                    "Level 68: You had a 50% chance to obtain Skotos",
                    "Level 72: You are on rate to obtain Skotos",
                    "Level 75: You had a 50% chance to obtain Dark totem",
                    "Level 77: You had a 99% chance to Complete Skotizo",
                    "Level 77: You had a 99% chance to obtain Dark claw",
                    "Level 79: You are on rate to obtain Dark totem",
                    "Level 79: You had a 50% chance to obtain Jar of darkness",
                    "Level 83: You are on rate to obtain Jar of darkness",
                    "Level 83: You had a 50% chance to Green Log Skotizo",
                    "Level 86: You are on rate to Green Log Skotizo",
                    "Level 87: You had a 99% chance to obtain Skotos",
                    "Level 94: You had a 99% chance to obtain Dark totem",
                    "Level 98: You had a 99% chance to obtain Jar of darkness",
                    "Level 99: You had a 99% chance to Green Log Skotizo"
            )
    ),
    SHELLBANE_GRYPHON(
            "Shellbane Gryphon",
            "shellbane_gryphon",
            925,
            "game_icon_shellbanegryphon.png",
            List.of(
                    "Level 59: You had a 50% chance to Complete Shellbane Gryphon",
                    "Level 59: You had a 50% chance to obtain Belle's folly (tarnished)",
                    "Level 63: You are on rate to Complete Shellbane Gryphon",
                    "Level 63: You are on rate to obtain Belle's folly (tarnished)",
                    "Level 75: You had a 50% chance to obtain Jar of feathers",
                    "Level 78: You had a 99% chance to Complete Shellbane Gryphon",
                    "Level 78: You had a 99% chance to obtain Belle's folly (tarnished)",
                    "Level 79: You are on rate to obtain Jar of feathers",
                    "Level 79: You had a 50% chance to obtain Gull",
                    "Level 83: You are on rate to obtain Gull",
                    "Level 83: You had a 50% chance to Green Log Shellbane Gryphon",
                    "Level 86: You are on rate to Green Log Shellbane Gryphon",
                    "Level 94: You had a 99% chance to obtain Jar of feathers",
                    "Level 98: You had a 99% chance to obtain Gull",
                    "Level 99: You had a 99% chance to Green Log Shellbane Gryphon"
            )
    ),
    SCURRIUS(
            "Scurrius",
            "scurrius",
            943,
            "game_icon_scurrius.png",
            List.of(
                    "Level 34: You had a 50% chance to obtain 1x Scurrius Spine",
                    "Level 38: You are on rate to obtain 1x Scurrius Spine",
                    "Level 44: You had a 50% chance to Complete Scurrius",
                    "Level 47: You are on rate to Complete Scurrius",
                    "Level 53: You had a 99% chance to obtain 1x Scurrius Spine",
                    "Level 57: You had a 99% chance to Complete Scurrius",
                    "Level 79: You had a 50% chance to Green Log Scurrius",
                    "Level 79: You had a 50% chance to obtain Scurry",
                    "Level 83: You are on rate to Green Log Scurrius",
                    "Level 83: You are on rate to obtain Scurry",
                    "Level 99: You had a 99% chance to obtain Scurry",
                    "Level 99: You had a 99% chance to Green Log Scurrius"
            )
    ),
    SPINDEL(
            "Spindel",
            "spindel",
            1010,
            "game_icon_spindel.png",
            List.of(
                    "Level 59: You had a 50% chance to obtain Dragon pickaxe",
                    "Level 59: You had a 50% chance to obtain Dragon 2h sword",
                    "Level 62: You are on rate to obtain Dragon 2h sword",
                    "Level 62: You are on rate to obtain Dragon pickaxe",
                    "Level 64: You had a 50% chance to obtain Fangs of venenatis",
                    "Level 66: You had a 50% chance to obtain Treasonous ring",
                    "Level 68: You are on rate to obtain Fangs of venenatis",
                    "Level 68: You had a 50% chance to obtain Voidwaker gem",
                    "Level 69: You are on rate to obtain Treasonous ring",
                    "Level 72: You are on rate to obtain Voidwaker gem",
                    "Level 75: You had a 50% chance to Complete Spindel",
                    "Level 77: You are on rate to Complete Spindel",
                    "Level 78: You had a 99% chance to obtain Dragon pickaxe",
                    "Level 78: You had a 99% chance to obtain Dragon 2h sword",
                    "Level 79: You had a 50% chance to obtain Venenatis spiderling",
                    "Level 81: You had a 50% chance to Green Log Spindel",
                    "Level 83: You are on rate to obtain Venenatis spiderling",
                    "Level 83: You had a 99% chance to obtain Fangs of venenatis",
                    "Level 84: You are on rate to Green Log Spindel",
                    "Level 85: You had a 99% chance to obtain Treasonous ring",
                    "Level 87: You had a 99% chance to obtain Voidwaker gem",
                    "Level 88: You had a 99% chance to Complete Spindel",
                    "Level 98: You had a 99% chance to obtain Venenatis spiderling",
                    "Level 99: You had a 99% chance to Green Log Spindel"
            )
    ),
    VENENATIS(
            "Venenatis",
            "venenatis",
            1887,
            "game_icon_venenatis.png",
            List.of(
                    "Level 59: You had a 50% chance to obtain Fangs of venenatis",
                    "Level 62: You had a 50% chance to obtain Dragon pickaxe",
                    "Level 62: You had a 50% chance to obtain Dragon 2h sword",
                    "Level 63: You are on rate to obtain Fangs of venenatis",
                    "Level 65: You are on rate to obtain Dragon 2h sword",
                    "Level 65: You are on rate to obtain Dragon pickaxe",
                    "Level 65: You had a 50% chance to obtain Voidwaker gem",
                    "Level 69: You are on rate to obtain Voidwaker gem",
                    "Level 69: You had a 50% chance to obtain Treasonous ring",
                    "Level 72: You are on rate to obtain Treasonous ring",
                    "Level 75: You had a 50% chance to Complete Spindel",
                    "Level 77: You are on rate to Complete Spindel",
                    "Level 78: You had a 99% chance to obtain Fangs of venenatis",
                    "Level 79: You had a 50% chance to obtain Venenatis spiderling",
                    "Level 81: You had a 99% chance to obtain Dragon pickaxe",
                    "Level 81: You had a 50% chance to Green Log Spindel",
                    "Level 81: You had a 99% chance to obtain Dragon 2h sword",
                    "Level 83: You are on rate to obtain Venenatis spiderling",
                    "Level 84: You are on rate to Green Log Spindel",
                    "Level 84: You had a 99% chance to obtain Voidwaker gem",
                    "Level 88: You had a 99% chance to Complete Spindel",
                    "Level 88: You had a 99% chance to obtain Treasonous ring",
                    "Level 98: You had a 99% chance to obtain Venenatis spiderling",
                    "Level 99: You had a 99% chance to Green Log Spindel"
            )
    ),
    THE_HUEYCOATL(
            "The Hueycoatl",
            "the_hueycoatl",
            7083,
            "game_icon_thehueycoatl.png",
            List.of(
                    "Level 46: You had a 50% chance to obtain Soiled page",
                    "Level 49: You are on rate to obtain Soiled page",
                    "Level 53: You had a 50% chance to obtain Hueycoatl hide",
                    "Level 55: You had a 50% chance to obtain Huasca seed",
                    "Level 57: You are on rate to obtain Hueycoatl hide",
                    "Level 58: You are on rate to obtain Huasca seed",
                    "Level 64: You had a 50% chance to obtain Tome of earth (empty)",
                    "Level 64: You had a 99% chance to obtain Soiled page",
                    "Level 66: You had a 50% chance to obtain Dragon hunter wand",
                    "Level 68: You are on rate to obtain Tome of earth (empty)",
                    "Level 70: You are on rate to obtain Dragon hunter wand",
                    "Level 71: You had a 50% chance to Complete The Hueycoatl",
                    "Level 72: You had a 99% chance to obtain Hueycoatl hide",
                    "Level 74: You are on rate to Complete The Hueycoatl",
                    "Level 74: You had a 99% chance to obtain Huasca seed",
                    "Level 79: You had a 50% chance to obtain Huberte",
                    "Level 81: You had a 50% chance to Green Log The Hueycoatl",
                    "Level 83: You are on rate to obtain Huberte",
                    "Level 83: You had a 99% chance to obtain Tome of earth (empty)",
                    "Level 84: You are on rate to Green Log The Hueycoatl",
                    "Level 85: You had a 99% chance to obtain Dragon hunter wand",
                    "Level 86: You had a 99% chance to Complete The Hueycoatl",
                    "Level 98: You had a 99% chance to obtain Huberte",
                    "Level 99: You had a 99% chance to Green Log The Hueycoatl"
            )
    ),

    ROYAL_TITANS(
            "Royal Titans",
            "royal_titans",
            943,
            "game_icon_theroyaltitans.png",
            List.of(
                    "Level 27: You had a 50% chance to obtain Giantsoul amulet",
                    "Level 31: You are on rate to obtain Giantsoul amulet",
                    "Level 42: You had a 50% chance to obtain Fire element staff crown",
                    "Level 42: You had a 50% chance to obtain Deadeye prayer scroll",
                    "Level 42: You had a 50% chance to obtain Ice element staff crown",
                    "Level 42: You had a 50% chance to obtain Mystic vigour prayer scroll",
                    "Level 45: You had a 99% chance to obtain Giantsoul amulet",
                    "Level 46: You are on rate to obtain Deadeye prayer scroll",
                    "Level 46: You are on rate to obtain Fire element staff crown",
                    "Level 46: You are on rate to obtain Ice element staff crown",
                    "Level 46: You are on rate to obtain Mystic vigour prayer scroll",
                    "Level 52: You had a 50% chance to Complete Royal Titans",
                    "Level 54: You are on rate to Complete Royal Titans",
                    "Level 61: You had a 99% chance to obtain Fire element staff crown",
                    "Level 61: You had a 99% chance to obtain Deadeye prayer scroll",
                    "Level 61: You had a 99% chance to obtain Ice element staff crown",
                    "Level 61: You had a 99% chance to obtain Mystic vigour prayer scroll",
                    "Level 64: You had a 99% chance to Complete Royal Titans",
                    "Level 79: You had a 50% chance to Green Log Royal Titans",
                    "Level 79: You had a 50% chance to obtain Bran",
                    "Level 83: You are on rate to Green Log Royal Titans",
                    "Level 83: You are on rate to obtain Bran",
                    "Level 98: You had a 99% chance to obtain Bran",
                    "Level 99: You had a 99% chance to Green Log Royal Titans"
            )
    ),
    THERMONUCLEAR_SMOKE_DEVIL(
            "Thermonuclear Smoke Devil",
            "thermonuclear_smoke_devil",
            925,
            "game_icon_thermonuclearsmokedevil.png",
            List.of(    "Level 58: You had a 50% chance to obtain Occult necklace",
                    "Level 61: You are on rate to obtain Occult necklace",
                    "Level 61: You had a 50% chance to obtain Smoke battlestaff",
                    "Level 65: You are on rate to obtain Smoke battlestaff",
                    "Level 65: You had a 50% chance to Complete Thermonuclear smoke devil",
                    "Level 68: You are on rate to Complete Thermonuclear smoke devil",
                    "Level 75: You had a 50% chance to obtain Jar of smoke",
                    "Level 77: You had a 99% chance to obtain Occult necklace",
                    "Level 79: You are on rate to obtain Jar of smoke",
                    "Level 79: You had a 50% chance to obtain Pet smoke devil",
                    "Level 80: You had a 99% chance to obtain Smoke battlestaff",
                    "Level 81: You had a 99% chance to Complete Thermonuclear smoke devil",
                    "Level 83: You are on rate to obtain Pet smoke devil",
                    "Level 83: You had a 50% chance to Green Log Thermonuclear smoke devil",
                    "Level 86: You are on rate to Green Log Thermonuclear smoke devil",
                    "Level 94: You had a 99% chance to obtain Jar of smoke",
                    "Level 98: You had a 99% chance to obtain Pet smoke devil",
                    "Level 99: You had a 99% chance to Green Log Thermonuclear smoke devil"
            )
    ),

    VET_ION(
            "Vet'ion",
            "vet_ion",
            1887,
            "game_icon_vetion.png",
            List.of("Level 59: You had a 50% chance to obtain The Skull of vet'ion",
                    "Level 62: You had a 50% chance to obtain a Dragon 2h sword",
                    "Level 62: You had a 50% chance to obtain a Dragon pickaxe",
                    "Level 63: You are on rate to obtain The Skull of vet'ion",
                    "Level 65: You are on rate to obtain a Dragon 2h sword",
                    "Level 65: You are on rate to obtain a Dragon pickaxe",
                    "Level 65: You had a 50% chance to obtain a Voidwaker blade",
                    "Level 69: You are on rate to obtain a Voidwaker blade",
                    "Level 69: You had a 50% chance to obtain The Ring of the gods",
                    "Level 72: You are on rate to obtain The Ring of the gods",
                    "Level 75: You had a 50% chance to Complete Vet'ion",
                    "Level 77: You are on rate to Complete Vet'ion",
                    "Level 78: You had a 99% chance to obtain The Skull of vet'ion",
                    "Level 79: You had a 50% chance to obtain Vet'ion jr.",
                    "Level 81: You had a 50% chance to Green Log Vet'ion",
                    "Level 81: You had a 99% chance to obtain a Dragon 2h sword",
                    "Level 81: You had a 99% chance to obtain a Dragon pickaxe",
                    "Level 83: You are on rate to obtain Vet'ion jr.",
                    "Level 84: You are on rate to Green Log Vet'ion",
                    "Level 84: You had a 99% chance to obtain a Voidwaker blade",
                    "Level 88: You had a 99% chance to Complete Vet'ion",
                    "Level 88: You had a 99% chance to obtain The Ring of the gods",
                    "Level 98: You had a 99% chance to obtain Vet'ion jr.",
                    "Level 99: You had a 99% chance to Green Log Vet'ion"
            )
    ),
    VORKATH(
            "Vorkath",
            "vorkath",
            489,
            "game_icon_vorkath.png",
            List.of(
                    "Level 32: You had a 50% chance to obtain Vorkath's head",
                    "Level 35: You had a 100% chance to obtain Vorkath's head",
                    "Level 62: You had a 50% chance to obtain Dragonbone necklace",
                    "Level 65: You are on rate to obtain Dragonbone necklace",
                    "Level 73: You had a 50% chance to obtain Jar of decay",
                    "Level 73: You had a 50% chance to obtain Vorki",
                    "Level 77: You are on rate to obtain Jar of decay",
                    "Level 77: You are on rate to obtain Vorki",
                    "Level 78: You had a 50% chance to obtain Draconic visage",
                    "Level 78: You had a 50% chance to obtain Skeletal visage",
                    "Level 81: You had a 99% chance to obtain Dragonbone necklace",
                    "Level 82: You are on rate to obtain Draconic visage",
                    "Level 82: You are on rate to obtain Skeletal visage",
                    "Level 84: You had a 50% chance to Complete Vorkath",
                    "Level 86: You are on rate to Complete Vorkath",
                    "Level 86: You had a 50% chance to Green Log Vorkath",
                    "Level 88: You are on rate to Green Log Vorkath",
                    "Level 92: You had a 99% chance to obtain Jar of decay",
                    "Level 92: You had a 99% chance to obtain Vorki",
                    "Level 97: You had a 99% chance to obtain Draconic visage",
                    "Level 97: You had a 99% chance to obtain Skeletal visage",
                    "Level 98: You had a 99% chance to Complete Vorkath",
                    "Level 99: You had a 99% chance to Green Log Vorkath"
            )
    ),
    YAMA(
            "Yama",
            "yama",
            1132,
            "game_icon_yama.png",
            List.of(
                    "Level 27: You had a 50% chance to obtain Dossier",
                    "Level 30: You are on rate to obtain Dossier",
                    "Level 30: You had a 50% chance to obtain Barrel of demonic tallow (full)",
                    "Level 30: You had a 50% chance to obtain Oathplate shards",
                    "Level 33: You are on rate to obtain Oathplate shards",
                    "Level 33: You had a 50% chance to obtain Chasm teleport scroll",
                    "Level 34: You are on rate to obtain Barrel of demonic tallow (full)",
                    "Level 36: You are on rate to obtain Chasm teleport scroll",
                    "Level 36: You had a 50% chance to obtain Forgotten lockbox",
                    "Level 40: You are on rate to obtain Forgotten lockbox",
                    "Level 44: You had a 99% chance to obtain Dossier",
                    "Level 48: You had a 99% chance to obtain Oathplate shards",
                    "Level 49: You had a 99% chance to obtain Barrel of demonic tallow (full)",
                    "Level 51: You had a 99% chance to obtain Chasm teleport scroll",
                    "Level 55: You had a 99% chance to obtain Forgotten lockbox",
                    "Level 58: You had a 50% chance to obtain Soulflame horn",
                    "Level 62: You are on rate to obtain Soulflame horn",
                    "Level 65: You had a 50% chance to obtain Oathplate chest",
                    "Level 65: You had a 50% chance to obtain Oathplate helm",
                    "Level 65: You had a 50% chance to obtain Oathplate legs",
                    "Level 69: You are on rate to obtain Oathplate chest",
                    "Level 69: You are on rate to obtain Oathplate helm",
                    "Level 69: You are on rate to obtain Oathplate legs",
                    "Level 74: You had a 50% chance to Complete Yama",
                    "Level 76: You are on rate to Complete Yama",
                    "Level 77: You had a 99% chance to obtain Soulflame horn",
                    "Level 79: You had a 50% chance to obtain Yami",
                    "Level 81: You had a 50% chance to Green Log Yama",
                    "Level 83: You are on rate to obtain Yami",
                    "Level 84: You are on rate to Green Log Yama",
                    "Level 84: You had a 99% chance to obtain Oathplate chest",
                    "Level 84: You had a 99% chance to obtain Oathplate helm",
                    "Level 84: You had a 99% chance to obtain Oathplate legs",
                    "Level 86: You had a 99% chance to Complete Yama",
                    "Level 98: You had a 99% chance to obtain Yami",
                    "Level 99: You had a 99% chance to Green Log Yama"
            )
    ),
    ZULRAH(
            "Zulrah",
            "zulrah",
            299,
            "game_icon_zulrah.png",
            List.of(
                    "Level 50: You had a 50% chance to obtain Magic fang",
                    "Level 50: You had a 50% chance to obtain Serpentine visage",
                    "Level 50: You had a 50% chance to obtain Tanzanite fang",
                    "Level 50: You had a 50% chance to obtain Uncut onyx",
                    "Level 54: You are on rate to obtain Magic fang",
                    "Level 54: You are on rate to obtain Serpentine visage",
                    "Level 54: You are on rate to obtain Tanzanite fang",
                    "Level 54: You are on rate to obtain Uncut onyx",
                    "Level 60: You had a 50% chance to Complete Zulrah",
                    "Level 62: You are on rate to Complete Zulrah",
                    "Level 69: You had a 99% chance to obtain Magic fang",
                    "Level 69: You had a 99% chance to obtain Serpentine visage",
                    "Level 69: You had a 99% chance to obtain Tanzanite fang",
                    "Level 69: You had a 99% chance to obtain Uncut onyx",
                    "Level 71: You had a 50% chance to obtain Pet snakeling",
                    "Level 72: You had a 99% chance to Complete Zulrah",
                    "Level 74: You are on rate to obtain Pet snakeling",
                    "Level 78: You had a 50% chance to obtain Tanzanite mutagen",
                    "Level 78: You had a 50% chance to obtain Magma mutagen",
                    "Level 82: You are on rate to obtain Tanzanite mutagen",
                    "Level 82: You are on rate to obtain Magma mutagen",
                    "Level 85: You had a 50% chance to Green Log Zulrah",
                    "Level 87: You are on rate to Green Log Zulrah",
                    "Level 90: You had a 99% chance to obtain Pet snakeling",
                    "Level 97: You had a 99% chance to obtain Tanzanite mutagen",
                    "Level 97: You had a 99% chance to obtain Magma mutagen",
                    "Level 99: You had a 99% chance to Green Log Zulrah"
            )
    ),
    ;

    public final String kcName;

    /**
     * Name to use when reading from RuneLite hiscores APIs.
     * Defaults to kcName unless overridden via constructor.
     */
    public final String hiscoreName;

    public final String configKey;
    public final int xpPerKill;
    public final String iconFile;
    public final List<String> milestones;

    /**
     * Optional aliases (e.g., abbreviations like "kbd", "kq", etc.).
     * No constants need to be updated; this defaults to empty.
     */
    public final String[] aliases;

    /**
     * Backwards-compatible constructor (all your current enum constants use this).
     * aliases is optional (varargs) so existing constants do not need changes.
     */
    BossDefinition(String kcName, String configKey, int xpPerKill, String iconFile, List<String> milestones, String... aliases)
    {
        this(kcName, kcName, configKey, xpPerKill, iconFile, milestones, aliases);
    }

    /**
     * Optional constructor if you ever need the hiscore name to differ from kcName.
     * Example usage:
     * SOME_BOSS("KC Name", "Hiscore Name", "config_key", 500, "icon.png", milestones)
     */
    BossDefinition(String kcName, String hiscoreName, String configKey, int xpPerKill, String iconFile, List<String> milestones, String... aliases)
    {
        this.kcName = kcName;
        this.hiscoreName = (hiscoreName == null || hiscoreName.trim().isEmpty()) ? kcName : hiscoreName;
        this.configKey = configKey;
        this.xpPerKill = xpPerKill;
        this.iconFile = iconFile;
        this.milestones = milestones;
        this.aliases = (aliases == null) ? new String[0] : aliases;
    }

    /**
     * Helper: matches a provided name against kcName, hiscoreName, or aliases (case-insensitive).
     */
    public boolean matchesName(String name)
    {
        if (name == null)
        {
            return false;
        }

        String n = name.trim();
        if (n.equalsIgnoreCase(kcName) || n.equalsIgnoreCase(hiscoreName))
        {
            return true;
        }

        for (String a : aliases)
        {
            if (a != null && n.equalsIgnoreCase(a.trim()))
            {
                return true;
            }
        }

        return false;
    }
}



